name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:  # Job de pruebas (CI)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Clean pip cache
      run: |
        pip cache purge  # Limpiar cualquier caché viejo

    - name: Install Flask and Werkzeug specific versions
      run: |
        pip install Flask==2.2.2 Werkzeug==2.2.2  # Forzar la instalación de las versiones correctas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instalar las dependencias desde requirements.txt

    - name: Run tests
      run: |
        pytest  # Comando para ejecutar las pruebas con pytest

  deploy:  # Job de despliegue (CD)
    runs-on: ubuntu-latest
    needs: test  # El despliegue solo se ejecuta si las pruebas son exitosas
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Usando el secreto de AWS
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Usando el secreto de AWS
        aws-region: 'us-east-2'  # Cambia por tu región de AWS

    - name: Debug AWS Credentials (Optional)
      run: |
        aws sts get-caller-identity  # Verificar si las credenciales están funcionando correctamente

    - name: Install Elastic Beanstalk CLI
      run: |
        pip install awsebcli

    - name: Initialize Elastic Beanstalk environment
      run: |
        eb init -p python-3.9 proyecto-aws --region us-east-2  # Cambia 'flask-app' por el nombre de tu aplicación

    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy  # Desplegar la aplicación a Elastic Beanstalk
